#
# Copyright © 2016-2018 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-node
  namespace: thingsboard
spec:
  serviceName: test-node
  replicas: 1
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: test-node
  template:
    metadata:
      labels:
        app: test-node
    spec:
      containers:
      - name: server
        imagePullPolicy: Always
        image: vzikratyi/oauth2-mapper-test:latest
        ports:
        - containerPort: 10010
          name: main
        env:
        - name: REDIS_NODES
          value: "tb-redis:6379"
        - name: REDIS_CONNECTION_TYPE
          value: "cluster"
        envFrom:
        - configMapRef:
            name: tb-node-db-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: test-node
  namespace: thingsboard
spec:
  type: ClusterIP
  selector:
    app: tb-node
  ports:
  - port: 10010
    name: main